FROM ubuntu:20.04

WORKDIR /opt/beyond

COPY entrypoint.sh .
COPY beyond .
COPY beyond4 .

RUN apt-get update \
&& rm -rf /var/lib/apt/lists/* \
&& chmod 777 entrypoint.sh \
&& chmod 777 beyond \
&& chmod 777 beyond4

ENTRYPOINT ["./entrypoint.sh"]